select  DOM_SPEDIZIONE, N.CAP, COMUNE
	from ANAGRAFICA N, COMUNE C
	where C.COD_COMUNE= N.COD_COMUNE and C.COD_PROVINCIA= N.COD_PROVINCIA and
	N.CODICE_MEMBRO= 801406 and N.COD_DIP= 'FI' and
	not exists
	(select 1 from CAP_SPEDIZIONE where N.CAP between DAL_CAP and AL_CAP) and
	 exists
	(select distinct A.CODICE_ABBONATO from ABBONAMENTI A where A.CODICE_ABBONATO= N.CODICE_ABBONATO and A.COPIE_RESIDUE > 0 and (
TIPO_RIV= 0 OR TIPO_RIV= 1000 OR TIPO_RIV= 500));