drop table membri_gerarchica;
create table dbo.membri_gerarchica (
codice varchar(30) not null, 
codice_fam varchar(30) null,
id_parent int null, 
vc_parent nvarchar(60), not null,
cognome nvarchar(60) not null, 
nome nvarchar(30) not null, 
citta_nas nvarchar(60) null, 
prov_nas char(2) null, 
data_nas datetime null, 
cod_nazione char(3) null, 
cod_div char(1) not null, 
ind_dom nvarchar(60) null, 
cap_dom char(5) null, 
cod_com char(6) null, 
num_tel nvarchar(30) null, 
num_tel_2 nvarchar(30) null, 
e_mail nvarchar(60) null, 
cod_prof char(4) null, 
codice_stato char(3) null, 
pres_da nvarchar(60) null, 
data_cer datetime null,
luogo_cer nvarchar(60) null, 
cod_att_ist_1 char(3) null, 
cod_att_ist_2 char(3) null, 
codice_staff char(3) null, 
cod_studio char(2) null, 
flag_goh char(1) null, 
flag_tok char(1) null, 
flag_oma char(1) null, 
flag_er char(1) null, 
flag_dis char(1) null, 
cod_dis char(3) null, 
u_insert nvarchar(60) null, 
d_insert datetime null, 
u_ult_mod nvarchar(60) null, 
d_ult_mod datetime null, 
dt_attnpa datetime null, 
dt_noptai datetime null, 
dt_dectfedim datetime null, 
) ;
alter table dbo.membri_gerarchica add constraint xpk_codice primary key nonclustered (codice) ;
create clustered index xdk_cognome on dbo.membri_gerarchica (cognome ) ;
create clustered index xdk_nodo on dbo.membri_gerarchica (id_parent ) ;
create clustered index xdk_vc_parent on dbo.membri_gerarchica (vc_parent ) ;