drop table aspiranti;
CREATE TABLE dbo.aspiranti 
(id decimal(18) NOT NULL,
codice varchar(30) NOT NULL,
vc_parent varchar(60) NOT NULL,
cognome varchar(60) NOT NULL, 
nome varchar(60) NOT NULL, 
citta_nas char(60) NULL, 
prov_nas char(2) NULL, 
data_nas datetime NOT NULL, 
cod_nazione char(3) NOT NULL, 
cod_div char(1) NOT NULL, 
ind_dom char(60) NOT NULL, 
cap_dom char(5) NOT NULL, 
cod_com char(6) NOT NULL, 
num_tel char(60) NULL, 
num_tel_2 char(60) NULL, 
e_mail char(60) NULL, 
cod_prof char(3) NULL, 
membro char(1) NULL, 
pres_da char(60) NULL, 
tipo_goh char(3) NOT NULL, 
u_insert char(30) NULL, 
d_insert datetime NULL  ) ;
